package cazcade.fountain.common.service.spring;

import org.springframework.beans.factory.FactoryBean;

import javax.annotation.Nonnull;

/**
 * Simple factory bean that facilitates the accessing an object as its string representation generated by toString().
 */
public class ObjectToStringFactoryBean implements FactoryBean {

    private final Object object;

    public ObjectToStringFactoryBean(Object object) {
        this.object = object;
    }

    public Object getObject() throws Exception {
        return object.toString();
    }

    @Nonnull
    public Class getObjectType() {
        return String.class;
    }

    public boolean isSingleton() {
        return false;
    }
}
